name: Android APK Build Engine

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Unzip Project
      run: |
        unzip netlimit-vpn.zip -d .
        # Agar zip ke andar folder hai, toh wahan se build chalayenge
        cd $(unzip -l netlimit-vpn.zip | grep '/$' | head -n1 | awk '{print $4}') || cd .

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Output APK
      uses: actions/upload-artifact@v4
      with:
        name: NetLimiter-APK
        path: app/build/outputs/apk/debug/app-debug.apk
